GH actions pls

diff --git a/.github/workflows/check_release_notes.yml b/.github/workflows/check_release_notes.yml
--- a/.github/workflows/check_release_notes.yml
+++ b/.github/workflows/check_release_notes.yml
@@ -67,9 +67,9 @@ jobs:
         echo "Found FCS version: ${FCS_VERSION}"
         echo "Found Visual Studio version: ${VISUAL_STUDIO_VERSION}"
 
-        [[ "$FSHARP_CORE_VERSION" =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]] || (echo "Invalid FSharp.Core Version parsed"; exit 1)
-        [[ "$FCS_VERSION" =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]] || (echo "Invalid FCS Version parsed"; exit 1)
-        [[ "$VISUAL_STUDIO_VERSION" =~ ^[0-9]+\.[0-9]+$ ]] || (echo "Invalid Visual Studio Version parsed"; exit 1)
+        [[ "$FSHARP_CORE_VERSION" =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]] || (echo "  Invalid FSharp.Core Version parsed"; exit 1)
+        [[ "$FCS_VERSION" =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]] || (echo "  Invalid FCS Version parsed"; exit 1)
+        [[ "$VISUAL_STUDIO_VERSION" =~ ^[0-9]+\.[0-9]+$ ]] || (echo "   Invalid Visual Studio Version parsed"; exit 1)
 
         _release_notes_base_path='docs/release-notes'
         _fsharp_core_release_notes_path="${_release_notes_base_path}/FSharp.Core/${FSHARP_CORE_VERSION}.md"
@@ -102,22 +102,26 @@ jobs:
 
             # Check if path is in modified files:
             if [[ "${_modified_paths[@]}" =~ "${path}" ]]; then
-                echo "Found $path in modified files"
-                echo "Checking if release notes modified in: $release_notes"
+                echo "  Found $path in modified files"
+                echo "      Checking if release notes modified in: $release_notes"
                 if [[ "${_modified_paths[@]}" =~ "${release_notes}" ]]; then
-                    echo "Found $release_notes in modified files"
-                    echo "Checking for pull request URL in $release_notes"
+                    echo "          Found $release_notes in modified files"
+                    echo "              Checking for pull request URL in $release_notes"
                     _pr_link_occurences=`grep -c "${PR_URL}" $release_notes`
+
+                    echo "              Found $_pr_link_occurences occurences of $PR_URL in $release_notes"
+
                     if [[ ${_pr_link_occurences} = 1 ]]; then
+                        echo "                  Found pull request URL in $release_notes once"
                         RELEASE_NOTES_FOUND+="> | \\\`$path\\\` | \\\`$release_notes\\\` |"
                         RELEASE_NOTES_FOUND+=$'\n'
                     elif [[ ${_pr_link_occurences} -gt 1 ]]; then
-                        echo "Found pull request URL in $release_notes, but with more than one PR URL"
+                        echo "                  Found pull request URL in $release_notes, but with more than one PR URL"
                         DESCRIPTION="**More than one current pull request URL (${PR_URL}) found in release notes**"
                         RELEASE_NOTES_NOT_FOUND+="| \\\`$path\\\` | \\\`$release_notes\\\` | ${DESCRIPTION} |"
                         RELEASE_NOTES_NOT_FOUND+=$'\n'
                     else
-                        echo "Did not find pull request URL in $release_notes"
+                        echo "                  Did not find pull request URL in $release_notes"
                         DESCRIPTION="**No current pull request URL (${PR_URL}) found**"
                         RELEASE_NOTES_NOT_FOUND+="| \\\`$path\\\` | \\\`$release_notes\\\` | ${DESCRIPTION} |"
                         RELEASE_NOTES_NOT_FOUND+=$'\n'
